image: debian:bookworm
stages:
  - build
  # - publish
variables:
  DEBIAN_FRONTEND: noninteractive
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/usr/local/go/bin

build:
  stage: build
  before_script:
    - mkdir artifacts
    - apt update
    - apt install -qq -y build-essential libpng-dev libpng16-16 wget curl git
    - ulimit -n 8096
    - cd /tmp
    - wget -q https://go.dev/dl/go1.22.3.linux-amd64.tar.gz
    - echo "8920ea521bad8f6b7bc377b4824982e011c19af27df88a815e3586ea895f1b36 go1.22.3.linux-amd64.tar.gz" > go1.22.3.linux-amd64.tar.gz.sha256sum
    - sha256sum -c go1.22.3.linux-amd64.tar.gz.sha256sum
    - tar -C /usr/local -xzf go1.22.3.linux-amd64.tar.gz
    - cd -
  script:
    - git apply limitless.patch
    - cd server
    - make validate-go-version
    - make setup-go-work
    - make build-linux-amd64
    - cd -
    - mv server/bin/mattermost "artifacts/mattermost-$CI_COMMIT_TAG"
  artifacts:
    paths:
      - artifacts
  only:
    - tags
